# 声明一个名为network的networks,subnet为network的子网地址,默认网关是172.21.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '172.21.0.0/16'
## 遇到容器不停重启，首先怀疑是挂载目录读写执行权限问题
services:
  #### mysql ####
  mysql:
    image: bitnami/mysql:8.4
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/volumes/mysql/data:/bitnami/mysql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=4b21ac7296fdf64a2e72d1b77fe5866c
      - MYSQL_DATABASE=go-layout
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      network:
        ipv4_address: 172.21.0.11

  #### redis ####
  redis:
    image: bitnami/redis:7.4
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/local/volumes/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - /usr/local/volumes/redis/data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=c220e927b90466e41b772184bab2d376
      - REDIS_DATABASE=0
    networks:
      network:
        ipv4_address: 172.21.0.12
