app:
  name: go-gin-grpc-layout
  env: test
  version: 0.0.1
  id: 127.0.0.1

remote:
  type: etcd
  endpoint: 127.0.0.1:2379
  timeout: 5s

server:
  http:
    name: http
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    name: grpc
    addr: 0.0.0.0:9000
    timeout: 5s

data:
  mysql:
    driver: mysql
    source: root:4b21ac7296fdf64a2e72d1b77fe5866c@tcp(127.0.0.1:3306)/go-layout?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    db: 0
    addr: 127.0.0.1:6379
    password: "c220e927b90466e41b772184bab2d376"
    dialTimeout: 1s
    readTimeout: 0.4s
    writeTimeout: 0.6s

log:
  level: "info"
  format: "json"
  fileName: "./logs/server"
  maxSize: 24
  maxBackups: 1
  maxAge: 7
  compress: true

opentelemetry:
  jaeger:
    endpoint: "127.0.0.1:1234"
  prometheus:
    endpoint: "127.0.0.1:1234"