// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: grpc/v1/test.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestGRPC_Test_FullMethodName = "/api.grpc.v1.TestGRPC/Test"
)

// TestGRPCClient is the client API for TestGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPC 服务定义
type TestGRPCClient interface {
	// Test 测试
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type testGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewTestGRPCClient(cc grpc.ClientConnInterface) TestGRPCClient {
	return &testGRPCClient{cc}
}

func (c *testGRPCClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, TestGRPC_Test_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestGRPCServer is the server API for TestGRPC service.
// All implementations must embed UnimplementedTestGRPCServer
// for forward compatibility.
//
// GRPC 服务定义
type TestGRPCServer interface {
	// Test 测试
	Test(context.Context, *TestRequest) (*TestResponse, error)
	mustEmbedUnimplementedTestGRPCServer()
}

// UnimplementedTestGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestGRPCServer struct{}

func (UnimplementedTestGRPCServer) Test(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedTestGRPCServer) mustEmbedUnimplementedTestGRPCServer() {}
func (UnimplementedTestGRPCServer) testEmbeddedByValue()                  {}

// UnsafeTestGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestGRPCServer will
// result in compilation errors.
type UnsafeTestGRPCServer interface {
	mustEmbedUnimplementedTestGRPCServer()
}

func RegisterTestGRPCServer(s grpc.ServiceRegistrar, srv TestGRPCServer) {
	// If the following call pancis, it indicates UnimplementedTestGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestGRPC_ServiceDesc, srv)
}

func _TestGRPC_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestGRPCServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestGRPC_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestGRPCServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestGRPC_ServiceDesc is the grpc.ServiceDesc for TestGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.grpc.v1.TestGRPC",
	HandlerType: (*TestGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _TestGRPC_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/v1/test.proto",
}
